services:
  postgres:
    image: postgis/postgis:10-2.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "psql postgresql://postgres@:5432/postgres -c 'select 1;'" ]
      interval: 10s
      timeout: 5s
      retries: 20

  task-event:
    image: eclipse-temurin:17-alpine
    container_name: task-event
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: sh -c "java -jar ./build/libs/task-event-0.0.1-SNAPSHOT.jar"
    ports:
      - "8080:8080"