database:
  url: jdbc:postgresql://postgres:5432/postgres
  user: postgres
  password: postgres
  driver: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true

entity:
  path: com.yurueu.event.entity

springdoc:
  swagger-ui.path: /swagger-ui
  api-docs.path: /v3/api-docs
  packagesToScan: com.yurueu.event
  pathsToMatch: /**

spring:
  liquibase:
    change-log: classpath:databases/event/changelog.xml
    contexts: data, test_data
